# Generated by Django 6.0 on 2025-12-16 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_status'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='users.location'),
        ),
    ]
